DirectoryPath: "public"
CheckInternal: true
CheckExternal: false
CheckMailto: false
CheckFavicons: false
CheckDoctype: false
CheckImages: true
CheckAlt: true
IgnoreDirs:
  - "node_modules"
  - "_print"
